name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 4' 

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          bun src/main.ts

          if git diff-index --quiet HEAD; then
            npm publish --provenance --access public

            git add package.json

            git push
            git push --tags
          else
            echo "No changes detected. Skipping npm publish and git push."
          fi

